# Generated by Django 3.0.2 on 2020-04-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('long_description', models.TextField(max_length=4000, verbose_name='Long description')),
                ('image', models.URLField(verbose_name='Image')),
                ('language', models.CharField(max_length=256, verbose_name='Language')),
                ('category', models.CharField(max_length=256, verbose_name='Category')),
                ('subcategory', models.CharField(blank=True, max_length=256, verbose_name='Subcategory')),
                ('website', models.URLField(verbose_name='Website link')),
                ('copyright', models.CharField(max_length=256, verbose_name='Copyright')),
                ('type', models.CharField(choices=[('episodic', 'Episodic'), ('serial', 'Serial')], default='episodic', max_length=9, verbose_name='Type')),
                ('is_released_in_seasons', models.BooleanField(default=False, verbose_name='Is released in seasons?')),
                ('is_include_explicit_language', models.BooleanField(default=False, verbose_name='Is include explicit language?')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is blocked?')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is complete?')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='show.Author', verbose_name='author')),
            ],
            options={
                'verbose_name': 'show',
                'verbose_name_plural': 'show',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Episode number')),
                ('season_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Season number')),
                ('type', models.CharField(choices=[('full', 'Full'), ('trailer', 'Trailer'), ('bonus', 'Bonus')], default='full', max_length=8, verbose_name='Episode type')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is blocked?')),
                ('file_url', models.URLField(verbose_name='File url')),
                ('file_length', models.IntegerField(verbose_name='File size in bytes')),
                ('file_type', models.CharField(choices=[('audio/x-m4a', 'Audio X M4A'), ('audio/mpeg', 'Audio Mpeg'), ('video/quicktime', 'Video Quicktime'), ('video/mp4', 'Video Mp4'), ('video/x-m4v', 'Video X M4V'), ('application/pdf', 'Application Pdf')], default='audio/mpeg', max_length=24, verbose_name='File Type')),
                ('publication_date', models.DateTimeField(verbose_name='Publication date')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration in sec')),
                ('link', models.URLField(blank=True, verbose_name='Episode link')),
                ('image', models.URLField(blank=True, verbose_name='Image')),
                ('is_include_explicit_language', models.BooleanField(default=False, verbose_name='Is include explicit language?')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='show.Show', verbose_name='show')),
            ],
            options={
                'verbose_name': 'episode',
                'verbose_name_plural': 'episodes',
            },
        ),
    ]
